"""Adversarial synthetic cases (all invented; no real course material). expected = kind[/confidence].
Each case: (label, domain, fields, expected). Written BEFORE running anything against them."""
from datetime import timedelta

from .cases import A, R, T0


def E(title, minutes=75, all_day=None):
    return dict(name=title, is_event=True, start_at=T0, end_at=T0 + timedelta(minutes=minutes), all_day=all_day)


QZ = dict(types=["online_quiz"], quiz=True)
ADV = [
    # ------------------------------------------------ abbreviations / formatting (STEM college)
    ("MT1, single default group", "stem", A("MT1", ["none"], pts=100, group="Assignments", gcount=1, share=0.20), "midterm"),
    ("MT 2 in Exams group", "stem", A("MT 2", ["none"], pts=100, group="Exams", share=0.20), "midterm/high"),
    ("Midterm1 no space, Gradescope", "stem", A("Midterm1", ["external_tool"], pts=100, group="Assignments", gcount=1, share=0.15), "midterm"),
    ("Exam2 no space", "stem", A("Exam2", ["on_paper"], pts=100, group="Assignments", gcount=1, share=0.20), "test/high"),
    ("Quiz10 no space, Classic", "stem", A("Quiz10", **QZ, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Prelim 2", "stem", A("Prelim 2", ["none"], pts=100, group="Prelims", share=0.20), "midterm/high"),
    ("Exam #3", "stem", A("Exam #3", ["none"], pts=100, group="Exams", share=0.20), "test/high"),
    ("Final Exam (Cumulative)", "stem", A("Final Exam (Cumulative)", ["none"], pts=200, group="Final Exam", share=0.25), "final/high"),
    ("Quiz 7 Retake", "stem", A("Quiz 7 Retake", **QZ, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Take-home exam w/ essay-ish description", "stem", A("Take-Home Exam 2", ["online_upload"], pts=100, group="Assignments", gcount=1, share=0.15,
        desc="<p>Answer all four questions in about 1500 words, double-spaced, citing two course readings (MLA).</p>"), "test"),
    ("Pop quiz", "stem", A("Pop Quiz (unannounced)", ["none"], pts=10, group="Quizzes", share=0.01), "quiz/high"),
    ("Weekly reading quiz", "stem", A("Weekly Reading Quiz 6", **QZ, pts=3, group="Reading Quizzes", share=0.005), "quiz/high"),
    ("iClicker quiz (design: participation)", "stem", A("Lecture 9 iClicker Quiz", ["none"], pts=2, group="Participation"), "none"),
    ("Gradescope exam", "stem", A("Gradescope: Midterm Exam 1", ["external_tool"], pts=100, group="Exams", share=0.20), "midterm/high"),
    ("Respondus quiz, no suffix", "stem", A("Quiz 4 (Respondus)", **QZ, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Practice Exam (ungraded)", "stem", A("Practice Exam (ungraded)", **QZ, pts=0, omit=True), "none"),
    ("Exam 1 Study Guide", "stem", A("Exam 1 Study Guide", ["online_upload"], pts=5, group="Homework", share=0.01), "none"),
    ("Midterm Review Session as assignment", "stem", A("Midterm Review Session", ["not_graded"], pts=0, grading="not_graded"), "none"),
    ("Quiz corrections reversed order", "stem", A("Corrections - Quiz 3", ["online_upload"], pts=5, group="Homework", share=0.005), "none"),
    ("Exam wrapper reversed order", "stem", A("Wrapper - Exam 2", **QZ, pts=2, group="Participation", share=0.002), "none"),
    ("Problem set before exam", "stem", A("Problem Set 6 (due before Exam 2)", ["online_upload"], pts=20, group="Problem Sets", share=0.03), "none"),
    ("Calc: ratio test homework (WebAssign)", "stem", A("Section 11.4: Ratio Test", ["external_tool"], pts=10, group="WebAssign Homework", share=0.01), "none"),
    ("Calc: root tests, default group", "stem", A("11.6 Ratio and Root Tests", ["external_tool"], pts=10, group="Assignments", gcount=1, share=0.005), "none"),
    ("Stats: paired t-test lab", "stem", A("Lab 5: Paired t-Test", ["online_upload"], pts=20, group="Labs", share=0.02, rubric=R), "none"),
    ("Chem: flame test lab", "stem", A("Flame Test Lab", ["online_upload"], pts=20, group="Labs", share=0.02), "none"),
    ("EE lab: verb 'test'", "stem", A("Lab 7: Test Your Circuit", ["online_upload"], pts=20, group="Labs", share=0.02), "none"),
    ("Test Your Knowledge (subtype)", "stem", A("Test Your Knowledge: Chapter 3", **QZ, pts=5, group="Quizzes", share=0.01), "quiz/high"),
    ("Final Exam Prep Quiz (subtype)", "stem", A("Final Exam Prep Quiz", **QZ, pts=10, group="Quizzes", share=0.02), "quiz/medium"),
    ("Classic-quiz homework 'Chapter 3 Problems'", "stem", A("Chapter 3 Problems", **QZ, pts=10, group="Assignments", gcount=1, share=0.01), "none"),
    ("Classic-quiz homework 'no time limit'", "stem", A("Section 4.2", **QZ, pts=10, group="Assignments", gcount=1, share=0.01,
        desc="<p>There is no time limit and you may retake it as many times as you like before the due date.</p>"), "none"),
    ("Midterm whose description mentions a practice exam", "stem", A("Midterm Exam 1", ["on_paper"], pts=100, group="Exams", share=0.20,
        desc="<p>A practice exam is posted in Files. The exam covers chapters 1-4. Closed book; you will have 75 minutes.</p>"), "midterm/high"),
    ("Exam curve column", "stem", A("Exam 2 Curve", ["none"], pts=5, group="Exams", share=0.01), "none"),
    ("Exam extra credit item", "stem", A("Exam 1 Extra Credit", ["online_upload"], pts=5, group="Exams", share=0.01), "none"),
    ("Exam grade appeal", "stem", A("Exam 1 Grade Appeal", ["online_text_entry"], pts=0), "none"),
    ("Quiz answer key", "stem", A("Quiz 3 Answer Key", ["not_graded"], pts=0, grading="not_graded"), "none"),
    ("Graded survey, admin word only in head", "stem", A("Survey: Exam 1 Feedback", **QZ, pts=1, group="Assignments", gcount=1, share=0.002), "none"),
    ("Prelim solutions (Cornell)", "stem", A("Prelim 1 Solutions", ["not_graded"], pts=0, grading="not_graded"), "none"),
    ("Prelim corrections", "stem", A("Prelim 2 Corrections", ["online_upload"], pts=10, group="Homework", share=0.01), "none"),
    ("Key terms for exam (object of 'for')", "hum", A("Key Terms for Exam 2", ["online_upload"], pts=10, group="Homework", share=0.01), "none"),
    # ------------------------------------------------ CS
    ("Autograder test column", "cs", A("Autograder Tests: HW 4", ["external_tool"], pts=20, group="Programming Assignments", share=0.02), "none"),
    ("Unit Testing quiz (real quiz)", "cs", A("Unit Testing Quiz", **QZ, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Coding midterm (HackerRank)", "cs", A("Midterm Coding Exam (HackerRank)", ["external_tool"], pts=100, group="Exams", share=0.20), "midterm/high"),
    ("Test Plan deliverable", "cs", A("Test Plan: Sprint 3", ["online_upload"], pts=20, group="Projects", share=0.03), "none"),
    ("Take-home exam zip", "cs", A("Exam 2 (Take-home, submit .zip)", ["online_upload"], pts=100, group="Exams", share=0.15), "test/high"),
    # ------------------------------------------------ nursing / pre-med
    ("ATI proctored assessment", "nurs", A("ATI Fundamentals Proctored Assessment", ["external_tool"], pts=100, group="ATI", gcount=4, share=0.10), "test"),
    ("HESI exit exam", "nurs", A("HESI Exit Exam", ["external_tool"], pts=100, group="HESI", gcount=4, share=0.15), "test/high"),
    ("Dosage calc competency exam (P/F)", "nurs", A("Dosage Calculation Competency Exam", ["none"], pts=10, grading="pass_fail", group="Clinical", share=0.0), "test"),
    ("SOAP note on a physical exam", "nurs", A("SOAP Note: Focused Physical Exam", ["online_upload"], pts=20, group="Clinical Documentation", share=0.03, rubric=R), "none"),
    ("vSim mental status exam", "nurs", A("Mental Status Exam Simulation", ["external_tool"], pts=10, group="Simulations", gcount=4, share=0.02), "none"),
    ("TB skin test documentation", "nurs", A("TB Skin Test Documentation", ["online_upload"], pts=0, grading="pass_fail", group="Clinical Requirements"), "none"),
    ("Pharm exam w/ LockDown suffix", "nurs", A("Pharm Exam 3 (Cardiac Meds) - Requires Respondus LockDown Browser", **QZ, pts=100, group="Exams", share=0.15), "test/high"),
    ("NCLEX practice questions", "nurs", A("NCLEX Practice Questions Ch. 12", ["external_tool"], pts=5, group="Homework", share=0.005), "none"),
    ("Exam remediation", "nurs", A("Exam 2 Remediation", ["online_upload"], pts=10, group="Remediation", gcount=4, share=0.01), "none"),
    ("Anatomy practical with subtitle", "nurs", A("Anatomy Practical: Skeletal System", ["on_paper"], pts=100, group="Lab Practicals", share=0.10), "test/high"),
    ("Bone practical (parenthetical)", "nurs", A("Bone Practical (Lower Limb)", ["on_paper"], pts=50, group="Lab", share=0.06), "test"),
    ("Histology practical exam", "nurs", A("Histology Practical Exam 2", ["on_paper"], pts=50, group="Lab", share=0.08), "test"),
    # ------------------------------------------------ humanities
    ("Theology: Examination of Conscience", "hum", A("Examination of Conscience Reflection", ["online_text_entry"], pts=10, group="Reflections", share=0.02), "none"),
    ("Law/debate: cross-examination drill", "hum", A("Cross-Examination Drill", ["on_paper"], pts=10, group="In-Class Activities", share=0.02), "none"),
    ("Studio art: midterm critique", "hum", A("Midterm Critique", ["on_paper"], pts=100, group="Critiques", share=0.15), "none"),
    ("Writing: midterm conference", "hum", A("Midterm Conference", ["none"], pts=10, group="Writing Process", share=0.04), "none"),
    ("Journal: Final Thoughts", "hum", A("Final Thoughts", ["online_text_entry"], pts=10, group="Journals", share=0.02), "none"),
    ("In-class essay exam (real)", "hum", A("In-Class Essay Exam", ["on_paper"], pts=100, group="Exams", share=0.15), "test/high"),
    ("Map quiz with subtitle", "hum", A("Map Quiz: Europe", ["on_paper"], pts=20, group="Quizzes", share=0.03), "quiz/high"),
    ("Readings for midterm (marker)", "hum", A("Readings for Midterm (Week 7)", ["not_graded"], pts=0, grading="not_graded"), "none"),
    ("Final paper in lieu of exam", "hum", A("Final Paper (in lieu of final exam)", ["online_upload"], pts=100, group="Papers", share=0.25, rubric=R), "none"),
    # ------------------------------------------------ languages
    ("Spanish: Prueba on paper", "lang", A("Prueba 3 (Capítulo 2)", ["on_paper"], pts=50, group="Pruebas", share=0.05), "test"),
    ("Spanish: Examen parcial", "lang", A("Examen Parcial 2", ["on_paper"], pts=100, group="Exámenes", share=0.20), "midterm"),
    ("Spanish: Examen final", "lang", A("Examen Final", ["on_paper"], pts=150, group="Exámenes", share=0.25), "final/high"),
    ("Spanish: Examen oral", "lang", A("Examen oral 1", ["media_recording"], pts=50, group="Evaluaciones orales", share=0.10), "test"),
    ("Jesuit 'Daily Examen' reflection", "lang", A("Daily Examen Reflection", ["online_text_entry"], pts=5, group="Reflections", share=0.01), "none"),
    ("Vocab quiz Spanish chapter", "lang", A("Vocab Quiz Capítulo 3", **QZ, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Oral exam (speaking)", "lang", A("Oral Exam (Speaking)", ["media_recording"], pts=50, group="Speaking", share=0.10), "test"),
    ("Composición (in class)", "lang", A("Composición 2 (en clase)", ["on_paper"], pts=50, group="Composiciones", share=0.08), "none"),
    # ------------------------------------------------ high school / dual credit
    ("HS unit test", "hs", A("Unit 4 Test", ["none"], pts=100, group="Tests", share=0.10), "test/high"),
    ("HS post-test is the unit test", "hs", A("Unit 4 Post-Test", ["none"], pts=100, group="Summative", share=0.10), "test/high"),
    ("HS test retake form", "hs", A("Test Retake Form", ["online_text_entry"], pts=1, group="Classwork", share=0.001), "none"),
    ("HS final exam exemption form", "hs", A("Final Exam Exemption Form", ["online_upload"], pts=0), "none"),
    ("HS bellwork quiz", "hs", A("Bellwork Quiz 12", **QZ, pts=2, group="Classwork", share=0.005), "none"),
    ("HS Socratic seminar in Summative", "hs", A("Socratic Seminar", ["on_paper"], pts=100, group="Summative", share=0.10), "none"),
    ("HS semester exam = final", "hs", A("Semester Exam", ["on_paper"], pts=200, group="Semester Exam", share=0.20), "final/high"),
    ("HS quest in Major Grades", "hs", A("Quest 3", ["on_paper"], pts=50, group="Major Grades", share=0.04), "quiz"),
    ("HS syllabus quiz without colon", "hs", A("Syllabus & Course Policies Quiz", **QZ, pts=5, group="Quizzes", share=0.01), "none"),
    ("Academic honesty quiz", "hs", A("Academic Honesty Quiz", **QZ, pts=5, group="Assignments", gcount=1, share=0.005), "none"),
    ("AI use policy quiz", "hs", A("AI Use Policy Quiz", **QZ, pts=2, group="Assignments", gcount=1, share=0.002), "none"),
    ("Getting started quiz", "hs", A("Getting Started Quiz", **QZ, pts=5, group="Quizzes", share=0.01), "none"),
    ("HS test for absent students", "hs", A("Unit 3 Test - Absent Students Only", ["none"], pts=100, group="Tests", share=0.10), "test/medium"),
    ("HS test 'with LockDown Browser'", "hs", A("Unit 5 Test with LockDown Browser", **QZ, pts=100, group="Tests", share=0.10), "test/high"),
    ("Retake request reversed", "hs", A("Request a Retake: Quiz 4", ["online_text_entry"], pts=0), "none"),
    ("Mock AP exam", "hs", A("Mock AP Exam", ["on_paper"], pts=0, grading="not_graded"), "none"),
    ("Practice version label", "hs", A("Quiz 5 (Practice Version)", **QZ, pts=0, omit=True), "none"),
    ("Dual credit chapter test", "hs", A("Chapter 9 Test (Dual Credit Students)", ["none"], pts=100, group="Tests & Quizzes", share=0.08), "test/high"),
    # ------------------------------------------------ calendar events
    ("EV Exam Jam (review event)", "event", E("Exam Jam", 120), "none"),
    ("EV Mock Exam in class", "event", E("Mock Exam (in class)", 50), "none"),
    ("EV grades posted", "event", E("Exam 2 grades posted", 0, all_day=True), "none"),
    ("EV midterm conferences", "event", E("Midterm Conferences", 20), "none"),
    ("EV library open late for finals", "event", E("Library open late for finals", 360), "none"),
    ("EV study guide posted", "event", E("Exam 2 Study Guide Posted", 0, all_day=True), "none"),
    ("EV Quiz Bowl", "event", E("Quiz Bowl", 60), "none"),
    ("EV Midterm 1 (real)", "event", E("Midterm 1", 50), "midterm/high"),
    ("EV MT2 (abbrev)", "event", E("MT2 - 7pm, Hall B", 90), "midterm/high"),
    ("EV timed exam not all-day", "event", E("Exam 3", 0, all_day=False), "test"),
]

# ------------------------------------------------ guards: written after v2's first pass, to catch v2 over-reach
G_X = dict(types=["none"], pts=100, group="Exams", share=0.2)
GUARDS = [
    ("Speech Science Exam 2 (topic before noun)", "guard", A("Speech Science Exam 2", **G_X), "test/high"),
    ("Freshman Seminar Quiz 3", "guard", A("Freshman Seminar Quiz 3", **QZ, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Unit 6 Test: Speech and Debate", "guard", A("Unit 6 Test: Speech and Debate", **G_X), "test/high"),
    ("AP Calc AB Test 2", "guard", A("AP Calc AB Test 2", ["on_paper"], pts=100, group="Tests", share=0.1), "test/high"),
    ("Unit 3 Test A (version)", "guard", A("Unit 3 Test A", **G_X), "test/high"),
    ("Final Multiple Choice", "guard", A("Final Multiple Choice", ["on_paper"], pts=100, group="Final Exam", share=0.15), "final/high"),
    ("Neuro Exam 2 (nursing unit exam)", "guard", A("Neuro Exam 2", **G_X), "test/high"),
    ("Physical Exam Quiz (topic)", "guard", A("Physical Exam Quiz", **QZ, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Post-Lab Quiz 4", "guard", A("Post-Lab Quiz 4", **QZ, pts=5, group="Lab", share=0.01), "quiz"),
    ("Midterm Elections Quiz (topic)", "guard", A("Midterm Elections Quiz", **QZ, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Make-up for Exam 2", "guard", A("Make-up for Exam 2", **G_X), "test"),
    ("Midterm desc: scratch paper not graded", "guard", A("Midterm 2", ["on_paper"], pts=100, group="Exams", share=0.2,
        desc="<p>Calculators will not be allowed. Scratch paper will not be graded.</p>"), "midterm/high"),
    ("Review quiz in 'Review Quizzes' group", "guard", A("Chapter 4 Review Quiz", **QZ, pts=10, group="Review Quizzes", share=0.02), "quiz/medium"),
    ("Final Four Bracket Project", "guard", A("Final Four Bracket Project", ["online_upload"], pts=20, group="Projects", share=0.03), "none"),
    ("EV Grade 10 Biology Final Exam", "guard", E("Grade 10 Biology Final Exam", 120), "final/high"),
    ("EV Exam 1 - Room 120 (unchanged)", "guard", E("Exam 1 - Room 120", 50), "test/high"),
]
