"""Second adversarial batch, written BEFORE v2 was implemented and never used for tuning (blind check of v2)."""
from .adv import E, QZ
from .cases import A, R

X = dict(types=["none"], pts=100, group="Exams", share=0.2)
ADV2 = [
    ("Midterm #2", "stem", A("Midterm #2", ["on_paper"], pts=100, group="Exams", share=0.2), "midterm/high"),
    ("Mid-Sem Test 1", "stem", A("Mid-Sem Test 1", ["none"], pts=100, group="Tests", share=0.15), "midterm/high"),
    ("Final Exam - Part B", "stem", A("Final Exam - Part B (Free Response)", ["on_paper"], pts=100, group="Final Exam", share=0.15), "final/high"),
    ("Quiz Corrections Week 5", "stem", A("Quiz Corrections Week 5", ["online_upload"], pts=5, group="Homework", share=0.005), "none"),
    ("Reflection: Midterm Exam", "stem", A("Reflection: Midterm Exam", ["online_text_entry"], pts=5, group="Homework", share=0.01), "none"),
    ("Practice: Unit 2 Test", "hs", A("Practice: Unit 2 Test", **QZ, pts=0, omit=True), "none"),
    ("Exam 3 Score Adjustment", "stem", A("Exam 3 Score Adjustment", ["none"], pts=0), "none"),
    ("Exam 2 Seating Chart", "stem", A("Exam 2 Seating Chart", ["not_graded"], pts=0, grading="not_graded"), "none"),
    ("Professional Practice Exam (real)", "nurs", A("Professional Practice Exam", **X), "test/high"),
    ("Clinical Practice Exam 2 (real)", "nurs", A("Clinical Practice Exam 2", ["online_quiz"], quiz=True, pts=100, group="Exams", share=0.2), "test/high"),
    ("Integral & comparison tests HW", "stem", A("Integral Test and Comparison Test Homework", ["external_tool"], pts=10, group="Online Homework", share=0.01), "none"),
    ("Chi-square test lab", "stem", A("Chi-Square Test Lab", ["online_upload"], pts=20, group="Labs", share=0.02), "none"),
    ("Usability test report", "cs", A("Usability Test Report", ["online_upload"], pts=50, group="Projects", share=0.1), "none"),
    ("Test 3 (Chapters 7-9)", "hs", A("Test 3 (Chapters 7-9)", ["on_paper"], pts=100, group="Tests", share=0.12), "test/high"),
    ("Quiz w/ LockDown dash suffix", "stem", A("Chapter 7 Quiz - LockDown Browser", **QZ, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Quiz 2 - Lockdown Browser Practice", "stem", A("Quiz 2 - Lockdown Browser Practice", **QZ, pts=0), "none"),
    ("Midterm Exam 1 Grade column", "stem", A("Midterm Exam 1 Grade", ["none"], pts=100, group="Exams", share=0.2), "midterm/high"),
    ("Speech 2: Persuasive", "hum", A("Speech 2: Persuasive", ["media_recording"], pts=50, group="Speeches", share=0.1, rubric=R), "none"),
    ("Final Speech", "hum", A("Final Speech", ["media_recording"], pts=100, group="Speeches", share=0.15, rubric=R), "none"),
    ("Lab Practical Exam 1", "nurs", A("Lab Practical Exam 1", ["on_paper"], pts=100, group="Lab Practicals", share=0.1), "test/high"),
    ("Prueba de vocabulario", "lang", A("Prueba de vocabulario 4", **QZ, pts=10, group="Pruebas", share=0.02), "quiz"),
    ("Examen 1 (Capítulos 1-3)", "lang", A("Examen 1 (Capítulos 1-3)", ["on_paper"], pts=100, group="Exámenes", share=0.2), "test/high"),
    ("Teacher appreciation survey", "hs", A("Teacher Appreciation Week Survey", **QZ, pts=0), "none"),
    ("AP exam registration fee", "hs", A("AP Exam Registration Fee", ["none"], pts=0), "none"),
    ("Unit 6 Summative Assessment", "hs", A("Unit 6 Summative Assessment", ["none"], pts=100, group="Summative", share=0.1), "test/high"),
    ("Gallery walk in Summative", "hs", A("Gallery Walk", ["on_paper"], pts=50, group="Summative", share=0.08), "none"),
    ("Exam 1 review game", "hs", A("Exam 1 Review Game (Blooket)", ["none"], pts=5, group="Classwork"), "none"),
    ("Exam week study plan", "stem", A("Exam Week Study Plan", ["online_upload"], pts=5), "none"),
    ("Midterm self-assessment", "hum", A("Midterm Self-Assessment", ["online_text_entry"], pts=5), "none"),
    ("Finals prep packet", "hs", A("Finals Prep Packet", ["on_paper"], pts=10, group="Classwork"), "none"),
    ("Unit 1 Pretest", "hs", A("Unit 1 Pretest", **QZ, pts=10), "none"),
    ("Exam 2 (DRC extended time)", "stem", A("Exam 2 (DRC Extended Time)", **X), "test"),
    ("CITI training quiz", "nurs", A("CITI Training Quiz", **QZ, pts=5, group="Assignments", gcount=1, share=0.005), "none"),
    ("Title IX training quiz", "hs", A("Title IX Training Quiz", **QZ, pts=5, group="Assignments", gcount=1, share=0.005), "none"),
    ("EV midterm review w/ TA", "event", E("Midterm Exam Review w/ TA", 60), "none"),
    ("EV final exam section time", "event", E("Final Exam: Sec 01 8:00-10:00am", 120), "final/high"),
    ("EV exams returned", "event", E("Exams returned", 0, all_day=True), "none"),
    ("EV short online quiz", "event", E("Quiz 5 (online, 15 min)", 15), "quiz"),
]
