from .cases import A, E
X = dict(types=["none"], pts=100, group="Exams", share=0.2)
BLIND2 = [
    ("Exam #2", A("Exam #2", **X), "test/high"),
    ("EXAM 1 (Ch. 1-4)", A("EXAM 1 (Ch. 1-4)", **X), "test/high"),
    ("Mid Term Exam", A("Mid Term Exam", **X), "midterm/high"),
    ("Mid-Semester Exam", A("Mid-Semester Exam", **X), "midterm/high"),
    ("Hour Exam 3", A("Hour Exam 3", **X), "midterm/high"),
    ("Cumulative Final", A("Cumulative Final", ["none"], pts=200, group="Final", share=0.25), "final/high"),
    ("Final Examination - Section 002", A("Final Examination - Section 002", ["on_paper"], pts=150, group="Exams", share=0.3), "final/high"),
    ("Quizzes roll-up column", A("Quizzes", ["none"], pts=50, group="Quizzes", share=0.1), "quiz/high"),
    ("Common Assessment", A("Unit 6 Common Assessment", ["external_tool"], pts=50, group="Summative", share=0.1), "test/high"),
    ("CFA acronym only", A("CFA 3", ["none"], pts=10, group="Formative", share=0.02), "none"),
    ("Weekly quiz lockdown", A("Weekly Quiz 9 - Requires Respondus LockDown Browser", ["online_quiz"], quiz=True, pts=10, group="Quizzes", share=0.01), "quiz/high"),
    ("Concept Check", A("Concept Check 4", ["online_quiz"], quiz=True, pts=5, group="Concept Checks", share=0.01), "quiz/high"),
    ("Reading quiz w/ parenthetical", A("Chapter 10 Reading Quiz (open until class)", ["online_quiz"], quiz=True, pts=5, group="Reading Quizzes", share=0.008), "quiz/high"),
    ("Lab Safety Quiz", A("Lab Safety Quiz", ["online_quiz"], quiz=True, pts=5), "none"),
    ("Plagiarism tutorial", A("Plagiarism Tutorial and Test", ["external_tool"], pts=5), "none"),
    ("Take-home quiz", A("Quiz 8 (Take-home)", ["online_upload"], pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Optional corrections", A("Midterm Exam Corrections (optional)", ["online_upload"], pts=5, group="Extra Credit"), "none"),
    ("Post-exam survey", A("Post-Exam Survey", ["online_quiz"], quiz=True, pts=1), "none"),
    ("Retake", A("Exam 1 Retake", **X), "test/high"),
    ("Final portfolio", A("Final Portfolio", ["online_upload"], pts=100, group="Portfolio", share=0.2), "none"),
    ("Final reflection", A("Final Reflection", ["online_text_entry"], pts=10, group="Reflections", share=0.02), "none"),
    ("Final lab practical", A("Final Lab Practical", ["on_paper"], pts=100, group="Lab", share=0.1), "test"),
    ("Speaking test", A("Speaking Test 2", ["media_recording"], pts=50, group="Oral Assessments", share=0.1), "test/high"),
    ("Spelling test", A("Spelling Test 12", ["none"], pts=20, group="Tests", share=0.03), "test/high"),
    ("Group quiz", A("Group Quiz 2", ["on_paper"], pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("iRAT (no keyword)", A("iRAT 4", ["online_quiz"], quiz=True, pts=10, group="Readiness Assessments", share=0.01), "quiz/high"),
    ("Exam no points yet", A("Exam 3", ["none"], pts=None, group="Exams"), "test"),
    ("Exam room assignments item", A("Exam Room Assignments", ["none"], pts=0, grading="not_graded"), "none"),
    ("EV exam with time+room", E("Exam 3 — 7:00-8:30pm, Physics 203", 90), "test/high"),
    ("EV bare Quiz", E("Quiz", 20), "quiz/medium"),
    ("EV midterm exam week", E("Midterm Exam Week", 24 * 60), "none"),
    ("EV last day to drop", E("Last day to drop", 0), "none"),
]
