from .cases import A, E, R

HOLDOUT = [
    ("Final Exam Project", A("Final Exam Project", ["online_upload"], pts=100, group="Final Exam", share=0.20, rubric=R), "final/medium"),
    ("Quiz 2 Redo", A("Quiz 2 Redo", ["online_quiz"], quiz=True, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("Test 1 on paper", A("Test 1", ["on_paper"], pts=100, group="Tests", share=0.15), "test/high"),
    ("Midterm Quiz", A("Midterm Quiz", ["online_quiz"], quiz=True, pts=30, group="Quizzes", share=0.06), "quiz/high"),
    ("Final Quiz", A("Final Quiz", ["online_quiz"], quiz=True, pts=20, group="Quizzes", share=0.04), "quiz/high"),
    ("Exam Prep Worksheet", A("Exam Prep Worksheet", ["online_upload"], pts=10, group="Homework", share=0.01), "none"),
    ("Testimony analysis", A("Testimony Analysis", ["online_text_entry"], pts=20, group="Writing", share=0.03), "none"),
    ("Examining sources", A("Examining Primary Sources", ["online_upload"], pts=20, group="Homework", share=0.03), "none"),
    ("Contest entry", A("Poster Contest Entry", ["online_upload"], pts=10), "none"),
    ("Finalize topic", A("Finalize your topic", ["online_text_entry"], pts=5), "none"),
    ("Semi-final round", A("Debate semi-final round", ["none"], pts=20, group="Debates"), "none"),
    ("Final draft", A("Final Draft: Essay 3", ["online_upload"], pts=100, group="Essays", share=0.15, rubric=R), "none"),
    ("Lab quiz", A("Lab Quiz 3", ["online_quiz"], quiz=True, pts=10, group="Lab", share=0.01), "quiz/high"),
    ("EV date-only exam", E("Exam 2", 0), "test/medium"),
    ("EV midterm grades due", E("Midterm grades due", 0), "none"),
    ("Respondus Monitor quiz", A("Quiz 1 (Respondus Monitor)", ["online_quiz"], quiz=True, pts=10, group="Quizzes", share=0.02), "quiz/high"),
    ("In-class exam", A("In-Class Exam 2", ["none"], pts=100, group="Exams", share=0.2), "test/high"),
    ("Exam grade column", A("Exam 1 Grade", ["none"], pts=100, group="Exams", share=0.2), "test/high"),
    ("Take-home final PDF", A("Final Exam (Take-Home)", ["online_upload"], pts=100, group="Final Exam", share=0.2,
                               desc="<p>Submit your PDF by Friday.</p>"), "final/high"),
    ("Essay exam", A("Essay Exam 2", ["online_text_entry"], pts=100, group="Exams", share=0.15), "test/medium"),
    ("Problem set", A("Problem Set 4", ["online_upload"], pts=20, group="Problem Sets", share=0.03), "none"),
    ("Quiz reflection", A("Weekly Quiz Reflection", ["online_text_entry"], pts=2, group="Participation"), "none"),
    ("Group exam", A("Group Exam 1", ["on_paper"], pts=50, group="Exams", share=0.1), "test/high"),
    ("Exam study session item", A("Final Exam Study Session", ["none"], pts=0, grading="not_graded"), "none"),
    ("Exam 2 Prep", A("Exam 2 Prep", ["online_upload"], pts=5, group="Homework", share=0.005), "none"),
    ("Review quiz graded in quiz group", A("Chapter 3 Review Quiz", ["online_quiz"], quiz=True, pts=10, group="Quizzes", share=0.02), "quiz/medium"),
    ("Test corrections HS", A("Chapter 4 Test Corrections", ["on_paper"], pts=10, group="Classwork"), "none"),
    ("Pre-lecture quiz", A("Pre-lecture Quiz 5", ["online_quiz"], quiz=True, pts=2, group="Quizzes", share=0.004), "quiz/high"),
    ("Clicker quiz", A("Clicker Quiz 3", ["none"], pts=1, group="Participation"), "none"),
    ("Kahoot review", A("Kahoot review game", ["none"], pts=0), "none"),
    ("Retake request", A("Exam 1 Retake Request", ["online_text_entry"], pts=0), "none"),
    ("Unit test in CS w/o plural", A("Lab 6: Unit Test Your Stack", ["external_tool"], pts=10, group="Labs", share=0.02), "none"),
    ("Chapter test HS", A("Chapter 6 Test", ["none"], pts=60, group="Tests & Quizzes", share=0.08), "test/high"),
    ("Exam 2 in single-group unweighted course", A("Exam 2", ["none"], pts=100, group="Assignments", gcount=1, share=0.22), "test/high"),
    ("Midterm exam info item w/ points 0", A("Midterm Exam Information", ["none"], pts=0), "midterm/medium"),
    ("Quiz with practice in description only", A("Quiz 2", ["online_quiz"], quiz=True, pts=5, group="Quizzes", share=0.02,
                                                 desc="<p>Graded for completion; any attempt receives full credit.</p>"), "quiz/medium"),
    ("EV Final Exam room", E("Final Exam - Room 101", 120), "final/high"),
    ("EV Exam 1 conflict sitting", E("Exam 1 Conflict Exam", 75), "test/medium"),
    ("EV Quiz 3 due", E("Quiz 3 due", 0), "none"),
    ("EV SI session", E("SI Session: Exam 2", 60), "none"),
]
