"""remove college odds

Revision ID: 00d3e604d559
Revises: 63eafcf4e6c6
Create Date: 2026-09-29 23:14:13.121808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d3e604d559'
down_revision = '63eafcf4e6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_college', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_college_user_id'))

    op.drop_table('saved_college')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gpa_scale')
        batch_op.drop_column('act')
        batch_op.drop_column('home_state')
        batch_op.drop_column('gpa')
        batch_op.drop_column('sat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sat', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('gpa', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('home_state', sa.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('act', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('gpa_scale', sa.FLOAT(), nullable=False))

    op.create_table('saved_college',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('scorecard_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=300), nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), nullable=True),
    sa.Column('state', sa.VARCHAR(length=2), nullable=True),
    sa.Column('public', sa.BOOLEAN(), nullable=True),
    sa.Column('admit_rate', sa.FLOAT(), nullable=True),
    sa.Column('oos_admit_rate', sa.FLOAT(), nullable=True),
    sa.Column('sat25', sa.INTEGER(), nullable=True),
    sa.Column('sat75', sa.INTEGER(), nullable=True),
    sa.Column('act25', sa.INTEGER(), nullable=True),
    sa.Column('act75', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_college', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_college_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###
