"""sync safety, grading settings, session versions

Revision ID: 0fdbf0d8108d
Revises: fba58d423de8
Create Date: 2026-09-29 20:57:37.395084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdbf0d8108d'
down_revision = 'fba58d423de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('omit_from_final_grade', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('assignment_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('never_drop', sa.JSON(), nullable=True))

    with op.batch_alter_table('canvas_file', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_weighting', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('roster_ids', sa.JSON(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('roster_ids')
        batch_op.drop_column('group_weighting')

    with op.batch_alter_table('canvas_file', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('assignment_group', schema=None) as batch_op:
        batch_op.drop_column('never_drop')

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('omit_from_final_grade')

    # ### end Alembic commands ###
