"""ai cost tracking and unchanged sync skip

Revision ID: 2878ebd39b8b
Revises: d8e110a9cd6d
Create Date: 2026-09-30 13:13:55.663892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2878ebd39b8b'
down_revision = 'd8e110a9cd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cache_write_tokens', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('cache_read_tokens', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('cost_usd', sa.Float(), nullable=True))

    with op.batch_alter_table('canvas_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_snapshot_hash', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canvas_account', schema=None) as batch_op:
        batch_op.drop_column('last_snapshot_hash')

    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_column('cost_usd')
        batch_op.drop_column('cache_read_tokens')
        batch_op.drop_column('cache_write_tokens')

    # ### end Alembic commands ###
