"""initial schema

Revision ID: 290b6b6398a2
Revises: 
Create Date: 2026-09-29 19:48:52.330139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290b6b6398a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_terms_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('grade_level', sa.String(length=40), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('plan_status', sa.String(length=40), nullable=True),
    sa.Column('plan_comped', sa.Boolean(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('gpa_scale', sa.Float(), nullable=False),
    sa.Column('sat', sa.Integer(), nullable=True),
    sa.Column('act', sa.Integer(), nullable=True),
    sa.Column('home_state', sa.String(length=2), nullable=True),
    sa.Column('study_minutes_per_day', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.String(length=10), nullable=True),
    sa.Column('show_on_leaderboards', sa.Boolean(), nullable=False),
    sa.Column('calendar_token', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_token')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_user_id'), ['user_id'], unique=False)

    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_token_user_id'), ['user_id'], unique=False)

    op.create_table('arcade_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=40), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('arcade_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arcade_run_user_id'), ['user_id'], unique=False)

    op.create_table('arcade_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arcade_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arcade_score_game'), ['game'], unique=False)
        batch_op.create_index(batch_op.f('ix_arcade_score_user_id'), ['user_id'], unique=False)

    op.create_table('canvas_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('canvas_user_id', sa.String(length=64), nullable=False),
    sa.Column('canvas_name', sa.String(length=200), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_snapshot_id', sa.String(length=80), nullable=True),
    sa.Column('restricted', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'host', 'canvas_user_id')
    )
    with op.batch_alter_table('canvas_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvas_account_user_id'), ['user_id'], unique=False)

    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_key', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_room_key'), ['room_key'], unique=False)

    op.create_table('coin_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ref')
    )
    with op.batch_alter_table('coin_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coin_transaction_user_id'), ['user_id'], unique=False)

    op.create_table('saved_college',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scorecard_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('admit_rate', sa.Float(), nullable=True),
    sa.Column('oos_admit_rate', sa.Float(), nullable=True),
    sa.Column('sat25', sa.Integer(), nullable=True),
    sa.Column('sat75', sa.Integer(), nullable=True),
    sa.Column('act25', sa.Integer(), nullable=True),
    sa.Column('act75', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_college', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_college_user_id'), ['user_id'], unique=False)

    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', 'source_id')
    )
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summary_user_id'), ['user_id'], unique=False)

    op.create_table('chat_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'reporter_id')
    )
    with op.batch_alter_table('chat_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_report_message_id'), ['message_id'], unique=False)

    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('course_code', sa.String(length=200), nullable=True),
    sa.Column('term_id', sa.String(length=64), nullable=True),
    sa.Column('term_name', sa.String(length=200), nullable=True),
    sa.Column('class_key', sa.String(length=400), nullable=False),
    sa.Column('room_key', sa.String(length=300), nullable=False),
    sa.Column('on_dashboard', sa.Boolean(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('current_grade', sa.String(length=20), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('final_grade', sa.String(length=20), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.Column('syllabus_html', sa.Text(), nullable=True),
    sa.Column('files_tab_hidden', sa.Boolean(), nullable=False),
    sa.Column('content_signature', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['canvas_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'canvas_id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_room_key'), ['room_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_user_id'), ['user_id'], unique=False)

    op.create_table('sync_run',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('files_needed', sa.Integer(), nullable=False),
    sa.Column('files_uploaded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['canvas_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_run_user_id'), ['user_id'], unique=False)

    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message_html', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'canvas_id')
    )
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_posted_at'), ['posted_at'], unique=False)

    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.String(length=64), nullable=False),
    sa.Column('group_canvas_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('unlock_at', sa.DateTime(), nullable=True),
    sa.Column('lock_at', sa.DateTime(), nullable=True),
    sa.Column('points_possible', sa.Float(), nullable=True),
    sa.Column('grading_type', sa.String(length=40), nullable=True),
    sa.Column('submission_types', sa.JSON(), nullable=True),
    sa.Column('is_quiz', sa.Boolean(), nullable=False),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=40), nullable=True),
    sa.Column('late', sa.Boolean(), nullable=False),
    sa.Column('missing', sa.Boolean(), nullable=False),
    sa.Column('excused', sa.Boolean(), nullable=False),
    sa.Column('workflow_state', sa.String(length=40), nullable=True),
    sa.Column('rubric', sa.JSON(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('rubric_assessment', sa.JSON(), nullable=True),
    sa.Column('user_done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'canvas_id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_due_at'), ['due_at'], unique=False)

    op.create_table('assignment_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('drop_lowest', sa.Integer(), nullable=False),
    sa.Column('drop_highest', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'canvas_id')
    )
    with op.batch_alter_table('assignment_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_group_course_id'), ['course_id'], unique=False)

    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('canvas_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['canvas_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'canvas_id')
    )
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_event_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_event_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_event_user_id'), ['user_id'], unique=False)

    op.create_table('canvas_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('canvas_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=800), nullable=True),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('canvas_updated_at', sa.String(length=64), nullable=True),
    sa.Column('wanted_version', sa.String(length=32), nullable=True),
    sa.Column('stored_version', sa.String(length=32), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('stored_at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_status', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['canvas_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'canvas_id')
    )
    with op.batch_alter_table('canvas_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvas_file_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canvas_file_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canvas_file_user_id'), ['user_id'], unique=False)

    op.create_table('content_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_chunk', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_course_source', ['course_id', 'source_type', 'source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_chunk_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_chunk_user_id'), ['user_id'], unique=False)

    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_user_id'), ['user_id'], unique=False)

    op.create_table('discussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message_html', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'canvas_id')
    )
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discussion_course_id'), ['course_id'], unique=False)

    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('unlock_at', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'canvas_id')
    )
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_course_id'), ['course_id'], unique=False)

    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('html_url', sa.String(length=500), nullable=True),
    sa.Column('canvas_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'slug')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_course_id'), ['course_id'], unique=False)

    op.create_table('practice_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('seconds_per_question', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_quiz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_quiz_user_id'), ['user_id'], unique=False)

    op.create_table('tutor_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutor_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutor_conversation_user_id'), ['user_id'], unique=False)

    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_deck_id'), ['deck_id'], unique=False)

    op.create_table('live_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('question_started_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rewarded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quiz_id'], ['practice_quiz.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_session_code'), ['code'], unique=True)

    op.create_table('quiz_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['practice_quiz.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempt_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempt_user_id'), ['user_id'], unique=False)

    op.create_table('tutor_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['tutor_conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tutor_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutor_message_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('live_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'nickname'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('live_player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_player_session_id'), ['session_id'], unique=False)

    op.create_table('live_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('choice', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['live_player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['live_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'question_index')
    )
    with op.batch_alter_table('live_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_answer_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_answer_session_id'))

    op.drop_table('live_answer')
    with op.batch_alter_table('live_player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_player_session_id'))

    op.drop_table('live_player')
    with op.batch_alter_table('tutor_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutor_message_conversation_id'))

    op.drop_table('tutor_message')
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempt_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempt_quiz_id'))

    op.drop_table('quiz_attempt')
    with op.batch_alter_table('live_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_session_code'))

    op.drop_table('live_session')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_deck_id'))

    op.drop_table('card')
    with op.batch_alter_table('tutor_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutor_conversation_user_id'))

    op.drop_table('tutor_conversation')
    with op.batch_alter_table('practice_quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_quiz_user_id'))

    op.drop_table('practice_quiz')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_course_id'))

    op.drop_table('page')
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_course_id'))

    op.drop_table('module')
    with op.batch_alter_table('discussion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discussion_course_id'))

    op.drop_table('discussion')
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_user_id'))

    op.drop_table('deck')
    with op.batch_alter_table('content_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_chunk_user_id'))
        batch_op.drop_index(batch_op.f('ix_content_chunk_course_id'))
        batch_op.drop_index('ix_chunk_course_source')

    op.drop_table('content_chunk')
    with op.batch_alter_table('canvas_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvas_file_user_id'))
        batch_op.drop_index(batch_op.f('ix_canvas_file_course_id'))
        batch_op.drop_index(batch_op.f('ix_canvas_file_account_id'))

    op.drop_table('canvas_file')
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_event_start_at'))
        batch_op.drop_index(batch_op.f('ix_calendar_event_account_id'))

    op.drop_table('calendar_event')
    with op.batch_alter_table('assignment_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_group_course_id'))

    op.drop_table('assignment_group')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_due_at'))
        batch_op.drop_index(batch_op.f('ix_assignment_course_id'))

    op.drop_table('assignment')
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_posted_at'))
        batch_op.drop_index(batch_op.f('ix_announcement_course_id'))

    op.drop_table('announcement')
    with op.batch_alter_table('sync_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_run_user_id'))

    op.drop_table('sync_run')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_room_key'))
        batch_op.drop_index(batch_op.f('ix_course_account_id'))

    op.drop_table('course')
    with op.batch_alter_table('chat_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_report_message_id'))

    op.drop_table('chat_report')
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summary_user_id'))

    op.drop_table('summary')
    with op.batch_alter_table('saved_college', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_college_user_id'))

    op.drop_table('saved_college')
    with op.batch_alter_table('coin_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coin_transaction_user_id'))

    op.drop_table('coin_transaction')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_room_key'))
        batch_op.drop_index(batch_op.f('ix_chat_message_created_at'))

    op.drop_table('chat_message')
    with op.batch_alter_table('canvas_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvas_account_user_id'))

    op.drop_table('canvas_account')
    with op.batch_alter_table('arcade_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arcade_score_user_id'))
        batch_op.drop_index(batch_op.f('ix_arcade_score_game'))

    op.drop_table('arcade_score')
    with op.batch_alter_table('arcade_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arcade_run_user_id'))

    op.drop_table('arcade_run')
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_user_id'))

    op.drop_table('api_token')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_created_at'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))

    op.drop_table('activity_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
