"""background text reading

Revision ID: 51b320ac2d02
Revises: 0fdbf0d8108d
Create Date: 2026-09-29 21:36:27.623704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b320ac2d02'
down_revision = '0fdbf0d8108d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canvas_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_started_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_canvas_file_text_status'), ['text_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canvas_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvas_file_text_status'))
        batch_op.drop_column('text_started_at')

    # ### end Alembic commands ###
