"""file fingerprints

Revision ID: 63eafcf4e6c6
Revises: 51b320ac2d02
Create Date: 2026-09-29 22:12:54.221560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63eafcf4e6c6'
down_revision = '51b320ac2d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canvas_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wanted_fingerprint', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('stored_fingerprint', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canvas_file', schema=None) as batch_op:
        batch_op.drop_column('stored_fingerprint')
        batch_op.drop_column('wanted_fingerprint')

    # ### end Alembic commands ###
