"""privacy fixes: no shared generations, opt-in chat and file sync, private live quizzes

Revision ID: 789c87c7f163
Revises: 90ce9bea669f
Create Date: 2026-09-30 18:11:58.936772

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '789c87c7f163'
down_revision = '90ce9bea669f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_generation')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_joined', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('sync_files', sa.Boolean(), nullable=True))
        batch_op.drop_column('roster_ids')

    with op.batch_alter_table('practice_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_course_files', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keep_all_files', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###
    # Data. Classes that already had files copied keep them (the student can untick them); every
    # other class waits for the student's choice. AI quizzes made before now may come from course
    # files, so they stay private. Leaderboards become opt-in. Signed Canvas links on turned-in files
    # and the text of discussion posts are dropped. Chat messages from before rooms were opt-in are
    # hidden (their audience was never asked).
    bind = op.get_bind()
    course = sa.table("course", sa.column("id", sa.Integer()), sa.column("sync_files", sa.Boolean()))
    canvas_file = sa.table("canvas_file", sa.column("course_id", sa.Integer()), sa.column("storage_key", sa.String()))
    has_files = sa.exists().where(canvas_file.c.course_id == course.c.id, canvas_file.c.storage_key.is_not(None))
    op.execute(course.update().where(has_files).values(sync_files=True))
    quiz = sa.table("practice_quiz", sa.column("source", sa.String()), sa.column("from_course_files", sa.Boolean()))
    op.execute(quiz.update().where(quiz.c.source == "ai").values(from_course_files=True))
    user = sa.table("user", sa.column("show_on_leaderboards", sa.Boolean()))
    op.execute(user.update().values(show_on_leaderboards=False))
    assignment = sa.table("assignment", sa.column("id", sa.Integer()), sa.column("attachments", sa.JSON()))
    for row_id, attachments in bind.execute(sa.select(assignment.c.id, assignment.c.attachments)
                                            .where(assignment.c.attachments.is_not(None))).all():
        cleaned = [{k: f.get(k) for k in ("id", "name", "content_type", "size")}
                   for f in attachments or [] if isinstance(f, dict)] or None
        if cleaned != attachments:
            bind.execute(assignment.update().where(assignment.c.id == row_id).values(attachments=cleaned))
    discussion = sa.table("discussion", sa.column("message_html", sa.Text()))
    op.execute(discussion.update().values(message_html=None))
    chat = sa.table("chat_message", sa.column("deleted", sa.Boolean()))
    op.execute(chat.update().values(deleted=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('keep_all_files')

    with op.batch_alter_table('practice_quiz', schema=None) as batch_op:
        batch_op.drop_column('from_course_files')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roster_ids', sa.JSON(), nullable=True))
        batch_op.drop_column('sync_files')
        batch_op.drop_column('chat_joined')

    op.create_table('shared_generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('uses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###
