"""privacy fixes: no shared generations, opt-in chat and file sync, private live quizzes

Revision ID: 789c87c7f163
Revises: 90ce9bea669f
Create Date: 2026-09-30 18:11:58.936772

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '789c87c7f163'
down_revision = '90ce9bea669f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_generation')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_joined', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('sync_files', sa.Boolean(), nullable=True))
        batch_op.drop_column('roster_ids')

    with op.batch_alter_table('practice_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_course_files', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keep_all_files', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###
    # Data: classes synced before this change keep their files (their students already had them
    # copied); AI quizzes made before it may come from course files, so they stay private; everyone's
    # leaderboard listing becomes opt-in. Whether new classes keep files is left for each student.
    course = sa.table("course", sa.column("sync_files", sa.Boolean()))
    op.execute(course.update().values(sync_files=True))
    quiz = sa.table("practice_quiz", sa.column("source", sa.String()), sa.column("from_course_files", sa.Boolean()))
    op.execute(quiz.update().where(quiz.c.source == "ai").values(from_course_files=True))
    user = sa.table("user", sa.column("show_on_leaderboards", sa.Boolean()))
    op.execute(user.update().values(show_on_leaderboards=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('keep_all_files')

    with op.batch_alter_table('practice_quiz', schema=None) as batch_op:
        batch_op.drop_column('from_course_files')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roster_ids', sa.JSON(), nullable=True))
        batch_op.drop_column('sync_files')
        batch_op.drop_column('chat_joined')

    op.create_table('shared_generation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('model', sa.VARCHAR(length=60), nullable=True),
    sa.Column('cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('uses', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###
