"""uploads, google integrations, chat attachments

Revision ID: 7f27aeaed785
Revises: 00d3e604d559
Create Date: 2026-09-29 23:27:00.495686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f27aeaed785'
down_revision = '00d3e604d559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind')
    )
    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_user_id'), ['user_id'], unique=False)

    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('text_status', sa.String(length=40), nullable=True),
    sa.Column('text_started_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_text_status'), ['text_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_user_id'), ['user_id'], unique=False)

    op.create_table('calendar_push',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.String(length=1024), nullable=False),
    sa.Column('calendar_id', sa.String(length=300), nullable=False),
    sa.Column('fingerprint', sa.String(length=40), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'assignment_id')
    )
    with op.batch_alter_table('calendar_push', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_push_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_push_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('tutor_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachments', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutor_conversation', schema=None) as batch_op:
        batch_op.drop_column('attachments')

    with op.batch_alter_table('calendar_push', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_push_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_push_assignment_id'))

    op.drop_table('calendar_push')
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_user_id'))
        batch_op.drop_index(batch_op.f('ix_upload_text_status'))
        batch_op.drop_index(batch_op.f('ix_upload_course_id'))

    op.drop_table('upload')
    with op.batch_alter_table('integration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_user_id'))

    op.drop_table('integration')
    # ### end Alembic commands ###
