"""shared generations and semester pass

Revision ID: 90ce9bea669f
Revises: 2878ebd39b8b
Create Date: 2026-09-30 13:19:27.601606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ce9bea669f'
down_revision = '2878ebd39b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('uses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('plan_payment_id', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plan_payment_id')
        batch_op.drop_column('plan_expires_at')

    op.drop_table('shared_generation')
    # ### end Alembic commands ###
