"""remove study plan

Revision ID: d8e110a9cd6d
Revises: 7f27aeaed785
Create Date: 2026-09-30 11:30:56.066653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e110a9cd6d'
down_revision = '7f27aeaed785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('study_minutes_per_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_minutes_per_day', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
