"""remove arcade

Revision ID: fba58d423de8
Revises: 290b6b6398a2
Create Date: 2026-09-29 20:01:46.200132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba58d423de8'
down_revision = '290b6b6398a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arcade_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arcade_score_game'))
        batch_op.drop_index(batch_op.f('ix_arcade_score_user_id'))

    op.drop_table('arcade_score')
    with op.batch_alter_table('arcade_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arcade_run_user_id'))

    op.drop_table('arcade_run')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arcade_run',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game', sa.VARCHAR(length=40), nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('arcade_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arcade_run_user_id'), ['user_id'], unique=False)

    op.create_table('arcade_score',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game', sa.VARCHAR(length=40), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arcade_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arcade_score_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_arcade_score_game'), ['game'], unique=False)

    # ### end Alembic commands ###
